version: 1.0.{build}
os: Visual Studio 2015
configuration:
- Static-Debug
- Debug
- Release
platform: x64
before_build:
- ps: win/utils/CSTYLE.ps1
build:
  project: win/NVML.sln
  verbosity: minimal
test_script:
- ps: win/test/RUNTESTS.ps1
